<a href="https://colab.research.google.com/github/shashi0101/DAVIS_lab_work/blob/main/Classwork/Numpy/Onesfunc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
x = np.ones([4,3], dtype='int')
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
