<a href="https://colab.research.google.com/github/shashi0101/DAVIS_lab_work/blob/main/Classwork/Numpy/ZerosfuncThreeD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
x = np.zeros([3,6,2], dtype='int')
print(x)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]
